_KEYname: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.YOUR_SECRED_KEY }}
        issue-message: "Thanks for reporting an issue"
        pr-message: "Let's give it a go, or a tug, or a pull"
